### ISSUE TITLE
Consider Creating a New Support Site/Area

### ISSUE THREAD

**Issue by Ngamer01** [ancestorak/brief#154]
https://forums.mozilla.org/viewtopic.php?f=23&t=14851&start=150#p48070

The previous support area (Mozilla Add-Ons Forum) has been closed due to the service moving to [Mozilla's new community forums](https://discourse.mozilla-community.org/c/add-ons).  If wanted, a new support site/area should be created.

**Comment by nohamelin** [comment]
That thread wasn't working as a proper support area since at least one or two years ago: it's full of posts from people who registered in that forum only to ask about Brief, getting practically all of them zero answers...  the closing helps, actually, to prevent to more people spending their time there pointlessly.

Though it can not be the proper tool, considering the few current action around Brief I think that having all in this tracker is Ok, where even support questions are done and tagged as such.

**Comment by tanriol** [comment]
Unfortunately, neither Adam (AFAIK) nor I have much time for support right now. I'd prefer to avoid creating a new support thread there unless someone volunteers to follow it and answer questions that arise there.

**Comment by Ngamer01** [comment]
I understand.  I used to help out when the support forums used to be on Brief's own homesite (at brief.mozdev.org/drupal).  When Mozdev had to shut Drupal down, I was unable to follow on to Mozilla's Add-On Forums until the very end due to events in my own life.

The reason for this suggestion was to ease the potential of review abuse at Mozilla's Add-Ons as people will leave zero-to-three star support questions in reviews with no official Brief support area currently (I know review abuse will still happen regardless, but the suggestion might help ease the frequency of that).

I'll leave the open to Ancestor to decide if opening a new support area is something he would like to do or if he would like to close this as won't fix.

**Comment by tanriol** [comment]
Hmm... maybe just set https://github.com/ancestorak/brief/issues as the support site for Brief?

**Comment by tanriol** [comment]
So I hope the support load would be light. The new support thread is [here](https://discourse.mozilla-community.org/t/support-brief/6514).
