### ISSUE TITLE
Brief is not able to search for numbers in the news feed

### ISSUE THREAD

**Issue by BellBiker** [ancestorak/brief#159]
Whenever you are searching for digits like 1609 the result of the feed list is empty. Searching for other characters works as expected.

Kind regards

**Comment by tanriol** [comment]
Unable to reproduce. Searched for 2015 and found lots of entries.

**Comment by BellBiker** [comment]
Hello again,
maybe I should first add some remarks about the system I was working on:
Windows 7
Firefox 40.0.3
Looking at the feeds of volksfreund.de, filtering with "wie" I got the feeds of screenshot. Due to an error I am not able to add a screenshot therefore I only add the feed summary text:

first  feed
Wenn Rap auf Orchester trifft und Pop auf den Totentanz - dann sind Sternstunden in Trier. Die gleichnamige Benefizgala spendet alle Erlöse an Flüchtlingskinder in Trier. Auftreten werden am 10. Oktober neben lokalen Musikgrößen, wie der Leiendecker Bloas oder Meike Anlauff, auch Thomas D. von den Fantastischen Vier. Die wichtigsten Gäste: die Flüchtlingskinder selbst.

second feed
Zum Abschluss der dritten Runde des Rheinlandpokals freut sich der TuS Mosella Schweich auf sein Spiel des Jahres gegen Eintracht Trier (Liveticker auf Fupa.net, 19.30 Uhr, Kunstrasenplatz). Der Rheinlandligist hofft auf mehr als 1000 Zuschauer. Eine Überraschung wie vor 55 Jahren - als Schweich Trier besiegte - scheint allerdings unrealistisch.

As you can see there are some numbers in like "10. Oktober", 55 "1000" and "19.30"

Searching for "1" doesn't return one of the feeds, 10 returns only the first feed, searching for 55 and 19 or 30 works fine, but 0 does not return any of the feeds and 1000 or 000 does not return the second feed. We also do have company internal feeds where we numbers are an important information and I cannot search for any numbers (e.g.25). 

Kind regards

**Comment by tanriol** [comment]
At least in some of the examples above the problem is not that these are numbers. Brief searches for full words by default. You can also search for words starting with your term like in `199*`. However, Brief cannot search for arbitrary characters in the middle or end of a word.

The underlying reason is that Brief does not search the (multi-megabyte) feed archive itself, but delegates the search to the full-text search feature of the sqlite database it uses. The search query is actually a [FTS search query](https://www.sqlite.org/fts3.html#section_3) which allows for neat tricks like `title:Bitcoin` for search in title only, but has no support for matching of the middle part of a string.

The only point I don't understand is `1000` not matching your second feed. I've found the same text snippet in [a feed](http://www.volksfreund.de/storage/rss/rss/regional.xml), and it works for me.

**Comment by BellBiker** [comment]
Ok,
thank you for the explanation. This shows me why most of the things don't work. Bad news. And it also shows me that I was wrong with my 1000. Trying some filters I maybe was to fast to wait for the result. But one more question. Can you tell me what the search use as word border. I guess <blank> and dot. What else?

**Comment by tanriol** [comment]
Brief currently uses the FTS3 "simple" tokenizer, which considers words to be sequences of English letters, digits and any non-ASCII characters. Thus, all the traditional punctuation like
```
 !"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~
```
newline and special characters should work.

**Comment by BellBiker** [comment]
I agree that brief works as defined therefore I can close the issue.
