### ISSUE TITLE
Websites open inside Brief's tab rather than new tab

### ISSUE THREAD

**Issue by Keith94** [ancestorak/brief#196]
Frequently when left clicking on new items to open them in a new tab, they will instead open inside the feed area of Brief's tab, for example like this YouTube page:

![snag 2016 07 20 20 01 17](https://cloud.githubusercontent.com/assets/5490615/17010106/b2cf5e2e-4eb5-11e6-9212-47baf877253d.png)

**Comment by Ngamer01** [comment]
I have an answer to this, but I can't confirm it 100% as the cause until tanriol and/or ancestor can look at it deeper.  What happens is when you're checking/auto-checking a feed at the same time as you're reading a feed and the checker finds there are new items within said feed to refresh the feed page and then you click on the item to open it in a new tab just as Brief is refreshing the feed page, the item's web address will instead open within Brief's tab instead of a new tab.

There are ways to workaround this problem including letting your manual/scheduled check run completely first before you begin reading feeds, stop said check until you finished reading, or disable checks until you're done reading (just remember to re-enable checks afterwards).

**Comment by Keith94** [comment]
The problem isn't related to checking for feed updates, it occurs frequently when updates are paused.

What I noticed is sometimes the Brief tab will get stuck in like a "loading state" where the tab shows a loading spinner. While it's happening, if I click on an item Brief forces it to open in the current tab rather than new one.

**Comment by MichaelEischer** [comment]
Does the problem also show up if you switch to _Show all items_ instead of _Show only unread items_ ?

I've found a simple way to reproduce this(?) problem:
Select _Show only unread items_ , then double-click the feed entry title.

**Comment by Keith94** [comment]
You're right, it only happens with the "show unread items" view... so when I double-click a new item, the bug happens every time.

Your patch seems to have fixed the bug for me. Thanks very much.
