### ISSUE TITLE
Migrate to WebExtensions

### ISSUE THREAD

**Issue by Keith94** [ancestorak/brief#248]
Are there plans to migrate Brief to WebExtensions API, so it can continue working in Firefox 57 and later?

**Comment by tanriol** [comment]
There are plans, but I lack time to do the work at the moment :-(

**Comment by tanriol** [comment]
Ok, so here's the brief status of Brief and WebExtension migration.

The Brief page is already non-XUL. There are still some UI elements in XUL, namely:
 - options page and feed settings page
 - CSS editing window
 - Brief toolbar button and its context menu

However, that's the minor problem, while the following one is more difficult. Brief uses several Firefox components that are not available to WebExtensions. These include the storage engine (WebExtensions have no access to `Sqlite.jsm` and/or any other SQL implementation) and the feed parser itself. Either we need to switch to non-sqlite storage (possibly something IndexedDB-based) or use something like `SQL.js`. A special point is that if we're migrating off sqlite, some other full-text search engine will be needed.

Finally, some of the Brief's functions cannot be currently implemented with WebExtensions. These include using livemarks for feed list and installing a handler for feeds. Brief can work without these, but less integrated and less comfortable.

**Comment by jnachtigall** [comment]
@tanriol Nice to see progress. With latest Nightly all legacy addons are disabled. So as a Nightly user I cannot use Brief anymore :-( But on the upside: In case you have any alpha/beta version as WebExtension ready, then let me know. Happy to test, since I really miss Brief a lot already (and there's no good alternative rss reader afaik).

**Comment by tanriol** [comment]
> So as a Nightly user I cannot use Brief anymore :-(

Actually it's the other way round. As Nightly users, we can go to `about:config`, flip `extensions.legacy.enabled`, restart Firefox and the addons are back... for now. But release users won't have this option.

**Comment by NgoHuy** [comment]
When will we have new webextension version, bro?

**Comment by jibe-b** [comment]
If this may help

from https://developer.mozilla.org/en-US/Add-ons/WebExtensions

>If you have ideas or questions, or need help migrating a legacy add-on to use WebExtension APIs, you can reach us on the dev-addons mailing list or #extdev on IRC.

A few suggestions (feedback welcome, I think while writing):

- Does it make sense to ask for an improvement of live bookmarks in Firefox, so that the database is accessible from webextensions? This could be by having live bookmarks as an extension using something like https://github.com/google/lovefield and thus, possibly enabling access to the database from other extensions

- if Brief has to handle RSS feed update, database storage and full-text search, maybe is https://github.com/WorldBrain/webmemex and https://github.com/WorldBrain/worldbrain an extension to start from in order to reuse code?

**Comment by tanriol** [comment]
> Does it make sense to ask for an improvement of live bookmarks in Firefox, so that the database is accessible from webextensions?

There's [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1276821) about this, but no one's working on it and it's already too late for Firefox 57.

> if Brief has to handle RSS feed update, database storage and full-text search, maybe is https://github.com/WorldBrain/webmemex and https://github.com/WorldBrain/worldbrain an extension to start from in order to reuse code?

Thank you for the links, I'll look into them.

> When will we have new webextension version, bro?

In a few weeks, I hope. Need to finalize the hybrid version this week and move on to the pure WebExtension one.

**Comment by will76** [comment]
Very excited to see it working on the amazing FF 57.

**Comment by tanriol** [comment]
Status update.

The current 2.5 alpha can migrate to WebExtensions storage the settings and the feed list, but not the items yet.

The pure-WebExtension work is not really started yet. Still, I hope to have at least a beta-quality version by mid-November (Firefox 57 release).

**Comment by etm** [comment]
Thanks. Your work is very appreciated.

**Comment by tanriol** [comment]
See #276 for WE alphas discussion.
