### ISSUE TITLE
Add favicons for all feeds

### ISSUE THREAD

**Issue by bdcomp** [ancestorak/brief#317]
For feeds without a site's favicon (displayed as general rss icon in the UI of Brief), it will be great to retrieve favicons by:

1. Looking at the home page of the feed, or
2. Externally, for example from Google, like this add-on:
https://addons.mozilla.org/firefox/addon/undo-closed-tabs-revived

Brief 2.5.5
Firefox 57
Kubuntu 17.10 64bit

**Comment by kbdave314** [comment]
I think the underlying issue here is that Brief only looks for favicons at favicon.ico under the website URL. That's where they are the majority of the time, but they can be anywhere in principle, and generally you have to check the value of the `href` attributes of the `link` elements with attribute `rel="icon"` for the corresponding website.

I have a [branch][branch] that checks the website as well as the website's origin for favicon URLs whenever looking for favicon.ico fails. It covers the 40% or so of my feeds that don't have favicons in the usual favicon.ico spot.

[branch]: https://github.com/kbdave314/brief/tree/robust-favicons
